// Turns a catalogue snapshot (tools/db/catalog.js) into SQL that recreates
// those objects, in dependency order:
//   extensions, types, sequences, tables (columns only), functions,
//   column defaults, constraints (FKs last), indexes, sequence ownership,
//   views, triggers, RLS, policies, privileges, comments.
// Function bodies are not checked at creation (check_function_bodies off,
// transaction-local), so the order of functions doesn't matter.
//
//   ddl(snapshot, { keep: (kind, obj) => boolean })
// kind: 'extension' | 'type' | 'sequence' | 'table' | 'column' | 'function' |
//       'constraint' | 'index' | 'view' | 'trigger' | 'policy' | 'comment'
'use strict';
const { ROLES, crlf } = require('./catalog');

const qi = (n) => (/^[a-z_][a-z0-9_]*$/.test(n) ? n : '"' + String(n).replace(/"/g, '""') + '"');
const lit = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const rel = (t) => 'public.' + qi(t);

function privileges(target, acl, cols) {
  // target: 'table public.x' / 'function public.f(args)' / 'sequence public.s'
  const out = [`revoke all on ${target} from ${ROLES.join(', ')};`];
  const by = {};
  for (const a of acl || []) if (ROLES.includes(a.g)) (by[a.g + (a.o ? '*' : '')] = by[a.g + (a.o ? '*' : '')] || []).push(a.p);
  for (const k of Object.keys(by).sort()) {
    const role = k.replace('*', '');
    out.push(`grant ${by[k].sort().join(', ').toLowerCase()}${cols ? ' (' + cols + ')' : ''} on ${target} to ${role}${k.endsWith('*') ? ' with grant option' : ''};`);
  }
  return out;
}

function ddl(s, opts = {}) {
  const keep = opts.keep || (() => true);
  const L = [];
  const sec = (title) => L.push('', '-- ' + title + ' ' + '-'.repeat(Math.max(3, 70 - title.length)));

  sec('Extensions');
  for (const e of s.extensions) if (keep('extension', e)) L.push(`create extension if not exists ${qi(e.extname)} with schema ${qi(e.nspname)};`);

  const types = s.types.filter((t) => keep('type', t));
  if (types.length) sec('Types');
  for (const t of types) {
    if (t.kind === 'e') L.push(`create type public.${qi(t.typname)} as enum (${(t.labels || []).map(lit).join(', ')});`);
    else if (t.kind === 'd') L.push(`create domain public.${qi(t.typname)} as ${t.base};`);
    else if (t.kind === 'c') L.push(`create type public.${qi(t.typname)} as (${t.attrs});`);
  }

  const seqs = s.sequences.filter((q) => keep('sequence', q) && !identitySeq(s, q));
  if (seqs.length) sec('Sequences');
  for (const q of seqs) L.push(`create sequence public.${qi(q.relname)} as ${q.type} increment by ${q.inc} minvalue ${q.min} maxvalue ${q.max} start with ${q.start} cache ${q.cache}${q.cycle ? ' cycle' : ''};`);

  const tables = s.relations.filter((r) => (r.kind === 'r' || r.kind === 'p') && keep('table', r));
  const tset = new Set(tables.map((t) => t.relname));
  const cols = s.columns.filter((c) => tset.has(c.tbl) && keep('column', c));
  sec('Tables');
  for (const t of tables) {
    const defs = cols.filter((c) => c.tbl === t.relname).map((c) => {
      let d = `  ${qi(c.attname)} ${c.type}`;
      if (c.collation) d += ` collate ${qi(c.collation)}`;
      if (c.gen === 's') d += ` generated always as (${c.default}) stored`;
      if (c.ident === 'a') d += ' generated always as identity';
      if (c.ident === 'd') d += ' generated by default as identity';
      if (c.not_null) d += ' not null';
      return d;
    });
    L.push(`create table ${rel(t.relname)} (\n${defs.join(',\n')}\n);`);
  }

  const fns = s.functions.filter((f) => keep('function', f));
  sec('Functions');
  for (const f of fns) L.push(crlf(f.def).trim() + ';', '');

  const dflt = cols.filter((c) => c.default != null && c.gen !== 's' && !c.ident);
  if (dflt.length) sec('Column defaults');
  for (const c of dflt) L.push(`alter table ${rel(c.tbl)} alter column ${qi(c.attname)} set default ${c.default};`);

  const cons = s.constraints.filter((k) => tset.has(k.tbl) && keep('constraint', k));
  sec('Constraints (foreign keys last)');
  for (const k of cons.filter((k) => k.type !== 'f').concat(cons.filter((k) => k.type === 'f')))
    L.push(`alter table ${rel(k.tbl)} add constraint ${qi(k.conname)} ${k.def};`);

  const idx = s.indexes.filter((i) => tset.has(i.tbl) && !i.constraint_backed && keep('index', i));
  if (idx.length) sec('Indexes');
  for (const i of idx) L.push(i.def + ';');

  const owned = s.sequences.filter((q) => keep('sequence', q) && q.owned_by && !identitySeq(s, q));
  for (const q of owned) { const [t, c] = q.owned_by.split('.'); L.push(`alter sequence public.${qi(q.relname)} owned by ${rel(t)}.${qi(c)};`); }

  const views = s.relations.filter((r) => (r.kind === 'v' || r.kind === 'm') && keep('view', r));
  if (views.length) sec('Views');
  for (const v of views) L.push(`create ${v.kind === 'm' ? 'materialized ' : ''}view ${rel(v.relname)} as\n${crlf(v.viewdef).trim().replace(/;$/, '')};`);

  const trg = s.triggers.filter((t) => keep('trigger', t));
  if (trg.length) sec('Triggers');
  for (const t of trg) L.push(t.def + ';' + (t.enabled === 'D' ? `\nalter table ${t.schema}.${qi(t.tbl)} disable trigger ${qi(t.tgname)};` : ''));

  sec('Row level security');
  for (const t of tables) {
    if (t.rls) L.push(`alter table ${rel(t.relname)} enable row level security;`);
    if (t.force_rls) L.push(`alter table ${rel(t.relname)} force row level security;`);
  }
  const pols = s.policies.filter((p) => tset.has(p.tbl) && keep('policy', p));
  for (const p of pols) {
    let d = `create policy ${qi(p.policyname)} on ${rel(p.tbl)} as ${p.permissive.toLowerCase()} for ${p.cmd.toLowerCase()} to ${p.roles.map(qi).join(', ')}`;
    if (p.qual != null) d += `\n  using (${p.qual})`;
    if (p.with_check != null) d += `\n  with check (${p.with_check})`;
    L.push(d + ';');
  }

  sec('Privileges (anon, authenticated, service_role, PUBLIC)');
  for (const t of tables.concat(views)) {
    L.push(...privileges('table ' + rel(t.relname), t.acl));
    for (const c of cols.filter((c) => c.tbl === t.relname && c.acl && c.acl.length)) {
      const by = {};
      for (const a of c.acl) if (ROLES.includes(a.g)) (by[a.g] = by[a.g] || []).push(a.p);
      for (const g of Object.keys(by).sort()) L.push(`grant ${by[g].sort().join(', ').toLowerCase()} (${qi(c.attname)}) on table ${rel(t.relname)} to ${g};`);
    }
  }
  for (const q of seqs) { const r = s.relations.find((x) => x.relname === q.relname); if (r) L.push(...privileges('sequence public.' + qi(q.relname), r.acl)); }
  for (const f of fns) L.push(...privileges(`function public.${qi(f.proname)}(${f.args})`, f.acl));

  sec('Comments');
  for (const t of tables.concat(views)) if (t.comment != null && keep('comment', { on: 'table', t })) L.push(`comment on ${t.kind === 'v' ? 'view' : 'table'} ${rel(t.relname)} is ${lit(crlf(t.comment))};`);
  for (const c of cols) if (c.comment != null && keep('comment', { on: 'column', c })) L.push(`comment on column ${rel(c.tbl)}.${qi(c.attname)} is ${lit(crlf(c.comment))};`);
  for (const f of fns) if (f.comment != null && keep('comment', { on: 'function', f })) L.push(`comment on function public.${qi(f.proname)}(${f.args}) is ${lit(crlf(f.comment))};`);
  for (const k of cons) if (k.comment != null) L.push(`comment on constraint ${qi(k.conname)} on ${rel(k.tbl)} is ${lit(crlf(k.comment))};`);
  for (const t of types) if (t.comment != null) L.push(`comment on type public.${qi(t.typname)} is ${lit(crlf(t.comment))};`);

  return L.join('\n') + '\n';
}

function identitySeq(s, q) {
  if (!q.owned_by) return false;
  const [t, c] = q.owned_by.split('.');
  const col = s.columns.find((x) => x.tbl === t && x.attname === c);
  return !!(col && col.ident);
}

module.exports = { ddl, qi, lit };
