// node tools/db/live-backup.js
//
// READ-ONLY logical backup of the live Supabase database into
// docs/database/live-backup-<timestamp>/ (gitignored):
//   schema.sql     DDL for every object in schema public (tools/db/ddl.js)
//   catalog.json   the catalogue snapshot it was made from (tools/db/catalog.js)
//   data/<table>.json   every row of every table in public, as a JSON array
//   manifest.json  time, server version, row count and sha256 per file
//
// SUPABASE_DB_URL is read from .env and never printed. Everything runs in
// one BEGIN READ ONLY transaction (REPEATABLE READ, so all tables come from
// the same moment) that ends in ROLLBACK.
//
// THE OUTPUT HOLDS SECRETS (shop secret phrases, device keys, passcode
// hashes, customer details). Never commit, share or upload it.
'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { Client } = require('pg');
const { snapshot } = require('./catalog');
const { ddl } = require('./ddl');

const ROOT = path.join(__dirname, '..', '..');
let URL = null;
for (const line of fs.readFileSync(path.join(ROOT, '.env'), 'utf8').split(/\r?\n/)) {
  const m = /^\s*SUPABASE_DB_URL\s*=\s*(.*)\s*$/.exec(line);
  if (m) URL = m[1].replace(/^["']|["']$/g, '');
}
if (!URL) { console.error('SUPABASE_DB_URL missing in .env'); process.exit(2); }
const redact = (s) => String(s).split(URL).join('[SUPABASE_DB_URL]').replace(/postgres(ql)?:\/\/\S+/g, '[db url]');
const sha = (b) => crypto.createHash('sha256').update(b).digest('hex');

(async () => {
  const stamp = new Date().toISOString().replace(/[:.]/g, '-');
  const dir = path.join(ROOT, 'docs', 'database', 'live-backup-' + stamp);
  const c = new Client({ connectionString: URL, ssl: { ca: fs.readFileSync(path.join(ROOT, 'supabase', 'prod-ca-2021.crt'), 'utf8'), rejectUnauthorized: true },
    connectionTimeoutMillis: 20000, statement_timeout: 120000, query_timeout: 180000 });
  c.on('error', (e) => { console.error('ERROR: ' + redact(e.message)); process.exit(1); });
  await c.connect();
  await c.query('begin isolation level repeatable read read only');
  const q = async (sql) => (await c.query(sql)).rows;
  if ((await q(`select current_setting('transaction_read_only') v`))[0].v !== 'on') throw new Error('not read-only; stopping');

  const snap = await snapshot(q);
  const tables = snap.relations.filter((r) => r.kind === 'r' || r.kind === 'p').map((r) => r.relname);
  fs.mkdirSync(path.join(dir, 'data'), { recursive: true });
  const files = {};
  const write = (rel, text) => { fs.writeFileSync(path.join(dir, rel), text); files[rel] = { bytes: Buffer.byteLength(text), sha256: sha(text) }; };
  write('catalog.json', JSON.stringify(snap, null, 1));
  write('schema.sql', `-- Schema of the live database (schema public), ${new Date().toISOString()}\n-- Generated by tools/db/live-backup.js. Restore notes: docs/database/backup-and-restore.md\n` +
    'begin;\nset local check_function_bodies = off;\n' + ddl(snap) + 'commit;\n');
  const rows = {};
  for (const t of tables) {
    const r = await q(`select coalesce(json_agg(x), '[]'::json)::text j, count(*)::int n from public.${'"' + t.replace(/"/g, '""') + '"'} x`);
    rows[t] = r[0].n;
    write(`data/${t}.json`, r[0].j);
  }
  await c.query('rollback');
  await c.end();
  const manifest = { taken_at: new Date().toISOString(), server_version: snap.server, read_only: true, tables: rows, files,
    warning: 'Contains secrets (shop phrases, device keys, passcode hashes, customer data). Never commit, share or upload.' };
  fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 1));
  const total = Object.values(files).reduce((a, f) => a + f.bytes, 0);
  console.log(JSON.stringify({ folder: path.relative(ROOT, dir), bytes: total, tables: rows }, null, 1));
})().catch((e) => { console.error('ERROR: ' + redact(e.message)); process.exit(1); });
